export interface SEOCity {
  slug: string;
  name: string;
  department: string;
  region: string;
  nearestAgencyId: string;
  nearestAgencyCity: string;
  heroImage: string;
  description: string;
  nearbyCitySlugs: string[];
}

export const SEO_CITIES: SEOCity[] = [
  {
    slug: 'paris',
    name: 'Paris',
    department: '75',
    region: 'Île-de-France',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/paris.webp',
    description:
      'Paris, capitale de la France et métropole mondiale, offre un réseau routier dense où le choix d\'un véhicule fiable est essentiel. Du périphérique aux rues du Marais, en passant par les boulevards haussmanniens et les quais de Seine, votre voiture d\'occasion doit être à la hauteur. Activ Automobiles sélectionne pour les Parisiens des véhicules adaptés à la conduite urbaine comme aux escapades vers Fontainebleau ou la Normandie. Chaque auto est contrôlée, garantie 12 mois et livrée directement dans votre arrondissement. Citadine compacte pour se garer facilement à Montmartre, SUV pour les week-ends en famille ou berline confortable pour les trajets professionnels : notre équipe vous accompagne avec un financement personnalisé et la reprise de votre ancien véhicule.',
    nearbyCitySlugs: ['argenteuil', 'saint-denis', 'montreuil'],
  },
  {
    slug: 'marseille',
    name: 'Marseille',
    department: '13',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/marseille.webp',
    description:
      'Marseille, cité phocéenne baignée de soleil, nécessite un véhicule endurant pour arpenter ses collines et ses quartiers variés. De la Corniche Kennedy au Vieux-Port, du Panier aux calanques de Sormiou, les routes marseillaises demandent une voiture fiable et bien entretenue. Activ Automobiles propose aux Marseillais un large choix d\'occasions contrôlées et garanties 12 mois, idéales pour la circulation urbaine et les virées vers Cassis ou Aix-en-Provence. Notre service de livraison à domicile couvre toute la métropole Aix-Marseille-Provence. Profitez d\'un financement adapté à votre budget, d\'une reprise avantageuse et de l\'expertise de nos techniciens certifiés pour rouler sereinement sous le soleil méditerranéen.',
    nearbyCitySlugs: ['nice', 'toulon', 'aix-en-provence'],
  },
  {
    slug: 'lyon',
    name: 'Lyon',
    department: '69',
    region: 'Auvergne-Rhône-Alpes',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/lyon.webp',
    description:
      'Lyon, capitale de la gastronomie et deuxième aire urbaine de France, séduit par ses traboules, ses quais de Saône et sa dynamique Confluence. Circuler entre la Presqu\'île, la Part-Dieu et les pentes de la Croix-Rousse exige un véhicule maniable et fiable. Activ Automobiles offre aux Lyonnais un catalogue varié de voitures d\'occasion inspectées et garanties 12 mois, parfaites pour le quotidien en ville et les échappées vers le Beaujolais ou les Alpes. Que vous habitiez Villeurbanne, Vénissieux ou Écully, nous livrons directement chez vous. Financement flexible, reprise au meilleur prix et conseils personnalisés : faites confiance à notre expertise pour votre prochain achat automobile à Lyon.',
    nearbyCitySlugs: ['saint-etienne', 'grenoble', 'clermont-ferrand'],
  },
  {
    slug: 'toulouse',
    name: 'Toulouse',
    department: '31',
    region: 'Occitanie',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/toulouse.webp',
    description:
      'Toulouse, la Ville Rose célèbre pour son industrie aéronautique et ses berges de la Garonne, offre un cadre de vie dynamique où la voiture reste indispensable. Du Capitole à Saint-Cyprien, de Blagnac aux coteaux de Pech-David, les Toulousains ont besoin d\'un véhicule fiable pour leurs trajets quotidiens et leurs week-ends dans les Pyrénées. Activ Automobiles met à votre disposition un large choix de véhicules d\'occasion vérifiés, garantis 12 mois et adaptés à tous les budgets. Notre service couvre toute la métropole toulousaine avec livraison à domicile. Bénéficiez d\'un financement sur mesure et d\'une reprise transparente pour changer de voiture en toute simplicité dans la capitale occitane.',
    nearbyCitySlugs: ['montpellier', 'perpignan', 'nimes'],
  },
  {
    slug: 'nice',
    name: 'Nice',
    department: '06',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/nice.webp',
    description:
      'Nice, joyau de la Côte d\'Azur, mêle élégance balnéaire et dynamisme urbain. De la Promenade des Anglais au Vieux-Nice, de Cimiez à l\'Arénas, la circulation niçoise requiert un véhicule agile et bien entretenu. Activ Automobiles accompagne les Niçois dans leur recherche de voiture d\'occasion avec un parc automobile contrôlé et garanti 12 mois. Citadines pour les ruelles du centre, SUV pour les excursions dans l\'arrière-pays mentonnais ou berlines pour rejoindre Monaco : chaque véhicule est sélectionné avec soin. Nous livrons dans toute la métropole Nice Côte d\'Azur et proposons un financement personnalisé ainsi qu\'un service de reprise. Roulez sereinement entre mer et montagnes avec Activ.',
    nearbyCitySlugs: ['marseille', 'toulon', 'aix-en-provence'],
  },
  {
    slug: 'nantes',
    name: 'Nantes',
    department: '44',
    region: 'Pays de la Loire',
    nearestAgencyId: 'agence-la-mothe-achard',
    nearestAgencyCity: 'La Mothe-Achard',
    heroImage: '/villes/nantes.webp',
    description:
      'Nantes, métropole de l\'Ouest dynamique et créative, séduit par son Château des Ducs, ses Machines de l\'île et ses bords de l\'Erdre. Pour naviguer entre le centre historique, l\'île de Nantes et les communes de Rezé, Saint-Herblain ou Orvault, un véhicule fiable est indispensable. Activ Automobiles propose aux Nantais un large catalogue d\'occasions vérifiées et garanties 12 mois depuis notre agence de La Mothe-Achard, facilement accessible par la N137. Nous livrons à domicile dans toute la Loire-Atlantique. Du break familial pour les vacances à La Baule au SUV pour les escapades dans le vignoble muscadet, trouvez le véhicule idéal avec un financement adapté et une reprise au meilleur prix.',
    nearbyCitySlugs: ['angers', 'le-mans', 'saint-nazaire'],
  },
  {
    slug: 'montpellier',
    name: 'Montpellier',
    department: '34',
    region: 'Occitanie',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/montpellier.webp',
    description:
      'Montpellier, cité méditerranéenne en plein essor, rayonne par sa Place de la Comédie, son quartier Antigone et ses plages à portée de main. La ville attire étudiants et jeunes actifs qui recherchent des véhicules fiables et accessibles. Activ Automobiles répond à cette demande avec un catalogue complet de voitures d\'occasion contrôlées et garanties 12 mois. Que vous circuliez dans l\'Écusson historique, vers les étangs de Palavas ou le Pic Saint-Loup, notre sélection couvre tous les usages et tous les budgets. Livraison à domicile dans l\'Hérault, financement souple et reprise de votre ancien véhicule : simplifiez votre achat automobile à Montpellier avec l\'accompagnement de nos conseillers experts.',
    nearbyCitySlugs: ['toulouse', 'perpignan', 'nimes'],
  },
  {
    slug: 'strasbourg',
    name: 'Strasbourg',
    department: '67',
    region: 'Grand Est',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/strasbourg.webp',
    description:
      'Strasbourg, capitale européenne au charme alsacien incomparable, enchante avec sa Petite France, sa cathédrale millénaire et ses institutions continentales. Circuler dans l\'Eurométropole, de Schiltigheim à Illkirch en passant par le Neudorf, nécessite un véhicule fiable toute l\'année, y compris durant les hivers rigoureux. Activ Automobiles propose aux Strasbourgeois un large choix de voitures d\'occasion inspectées et garanties 12 mois, avec livraison à domicile dans tout le Bas-Rhin. SUV équipés pour la neige, citadines pour le centre ou breaks pour les familles : notre catalogue s\'adapte à votre quotidien. Profitez d\'un financement personnalisé et d\'une reprise avantageuse pour votre prochain achat automobile en Alsace.',
    nearbyCitySlugs: ['reims', 'nancy', 'metz'],
  },
  {
    slug: 'bordeaux',
    name: 'Bordeaux',
    department: '33',
    region: 'Nouvelle-Aquitaine',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/bordeaux.webp',
    description:
      'Bordeaux, perle de l\'Aquitaine inscrite au patrimoine mondial, fascine par sa Place de la Bourse, son miroir d\'eau et ses quais animés. La métropole bordelaise, de Mérignac à Pessac en passant par Talence et Bègles, requiert un véhicule fiable pour les trajets quotidiens et les escapades dans le vignoble. Activ Automobiles vous accueille dans son agence bordelaise avec un parc de véhicules d\'occasion rigoureusement sélectionnés et garantis 12 mois. Berlines élégantes, citadines économiques ou SUV familiaux : trouvez l\'auto qui vous ressemble. Financement flexible, reprise au meilleur prix et livraison dans toute la Gironde pour un achat automobile en toute sérénité dans la capitale du vin.',
    nearbyCitySlugs: ['limoges', 'pau', 'la-rochelle'],
  },
  {
    slug: 'lille',
    name: 'Lille',
    department: '59',
    region: 'Hauts-de-France',
    nearestAgencyId: 'agence-talange',
    nearestAgencyCity: 'Talange',
    heroImage: '/villes/lille.webp',
    description:
      'Lille, capitale des Flandres au cœur généreux, charme par sa Grand-Place, sa Vieille Bourse et ses quartiers animés du Vieux-Lille. Métropole transfrontalière entre la France et la Belgique, Lille offre un réseau routier dense où un véhicule bien entretenu fait toute la différence. Activ Automobiles propose aux Lillois un vaste choix de voitures d\'occasion contrôlées et garanties 12 mois, idéales pour circuler entre Roubaix, Tourcoing et Villeneuve-d\'Ascq. Nos véhicules sont livrés à domicile dans tout le Nord. Du trajet quotidien au week-end à la côte d\'Opale, faites confiance à notre expertise et profitez d\'un financement adapté et d\'une reprise transparente de votre véhicule actuel.',
    nearbyCitySlugs: ['amiens', 'dunkerque', 'calais'],
  },
  {
    slug: 'rennes',
    name: 'Rennes',
    department: '35',
    region: 'Bretagne',
    nearestAgencyId: 'agence-rennes',
    nearestAgencyCity: 'Rennes',
    heroImage: '/villes/rennes.webp',
    description:
      'Rennes, vibrante capitale bretonne, séduit par sa Place des Lices, ses maisons à colombages et son dynamisme étudiant et technologique. Circuler dans la métropole rennaise, de Saint-Grégoire à Cesson-Sévigné en passant par Chantepie, demande un véhicule fiable au quotidien. Activ Automobiles Rennes vous propose un vaste catalogue de voitures d\'occasion vérifiées et garanties 12 mois directement dans son showroom de Saint-Grégoire. SUV pour les week-ends sur la côte d\'Émeraude, citadine pour le centre historique ou break pour les trajets familiaux : chaque véhicule est inspecté par nos techniciens. Profitez d\'un financement sur mesure, d\'une reprise avantageuse et d\'un accompagnement personnalisé.',
    nearbyCitySlugs: ['brest', 'nantes', 'le-havre'],
  },
  {
    slug: 'reims',
    name: 'Reims',
    department: '51',
    region: 'Grand Est',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/reims.webp',
    description:
      'Reims, cité des sacres et capitale du champagne, impressionne par sa cathédrale gothique et ses caves prestigieuses. La ville champenoise, avec ses boulevards larges et son réseau autoroutier vers Paris, Metz et Lille, nécessite un véhicule confortable et fiable. Activ Automobiles propose aux Rémois un choix varié de voitures d\'occasion inspectées et garanties 12 mois. Que vous traversiez le centre-ville vers la place Drouet-d\'Erlon ou que vous empruntiez l\'A4 pour vos déplacements professionnels, nos véhicules sont prêts à vous accompagner. Livraison à domicile dans la Marne, financement personnalisé et reprise de votre ancien véhicule : simplifiez votre achat auto à Reims avec Activ.',
    nearbyCitySlugs: ['strasbourg', 'nancy', 'metz'],
  },
  {
    slug: 'saint-etienne',
    name: 'Saint-Étienne',
    department: '42',
    region: 'Auvergne-Rhône-Alpes',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/saint-etienne.webp',
    description:
      'Saint-Étienne, ville au passé industriel devenue cité du design, se réinvente entre son centre animé et ses collines verdoyantes. Les pentes stéphanoises et les routes vers le Pilat ou Lyon exigent un véhicule robuste et bien entretenu. Activ Automobiles accompagne les Stéphanois avec un large catalogue de voitures d\'occasion contrôlées et garanties 12 mois. De Châteaucreux à Bellevue, de Firminy à Andrézieux, notre sélection couvre tous les besoins : citadine urbaine, SUV familial ou utilitaire pratique. Nous livrons dans toute la Loire et proposons un financement adapté ainsi qu\'une reprise au meilleur prix. Offrez-vous un véhicule fiable au cœur du Massif Central avec Activ Automobiles.',
    nearbyCitySlugs: ['lyon', 'grenoble', 'clermont-ferrand'],
  },
  {
    slug: 'le-havre',
    name: 'Le Havre',
    department: '76',
    region: 'Normandie',
    nearestAgencyId: 'agence-rennes',
    nearestAgencyCity: 'Rennes',
    heroImage: '/villes/le-havre.webp',
    description:
      'Le Havre, port emblématique de Normandie classé au patrimoine mondial pour son architecture Perret, allie caractère maritime et modernité urbaine. Entre le front de mer, le quartier Saint-François et les hauteurs de Sainte-Adresse, les Havrais ont besoin d\'un véhicule adapté aux reliefs de la ville et au climat atlantique. Activ Automobiles vous propose un catalogue de voitures d\'occasion vérifiées et garanties 12 mois, idéales pour vos trajets quotidiens comme pour les escapades vers Étretat ou Honfleur. Notre service de livraison couvre toute la Seine-Maritime. Financement souple, reprise transparente et conseil expert : achetez votre prochaine voiture au Havre en toute confiance.',
    nearbyCitySlugs: ['rouen', 'caen', 'paris'],
  },
  {
    slug: 'toulon',
    name: 'Toulon',
    department: '83',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/toulon.webp',
    description:
      'Toulon, première base navale de Méditerranée, séduit par sa rade spectaculaire, son mont Faron et ses marchés provençaux animés. La circulation toulonnaise, entre le centre-ville piétonnier et les communes de La Seyne, Ollioules ou La Valette, nécessite un véhicule maniable et fiable. Activ Automobiles offre aux Toulonnais un choix étendu de voitures d\'occasion contrôlées et garanties 12 mois, parfaites pour le littoral varois et les routes de l\'arrière-pays. Du cabriolet pour profiter du soleil au SUV pour les escapades dans le massif des Maures, trouvez votre bonheur. Livraison dans le Var, financement personnalisé et reprise avantageuse au programme.',
    nearbyCitySlugs: ['marseille', 'nice', 'aix-en-provence'],
  },
  {
    slug: 'grenoble',
    name: 'Grenoble',
    department: '38',
    region: 'Auvergne-Rhône-Alpes',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/grenoble.webp',
    description:
      'Grenoble, capitale des Alpes françaises, éblouit par son panorama montagnard, ses bulles du téléphérique de la Bastille et son dynamisme scientifique. Les routes grenobloises, entre la plaine de l\'Isère et les massifs de la Chartreuse, du Vercors et de Belledonne, exigent un véhicule performant en toute saison. Activ Automobiles propose aux Grenoblois des voitures d\'occasion inspectées et garanties 12 mois, adaptées aussi bien à la ville qu\'à la montagne. SUV à transmission intégrale, citadine compacte ou break familial : notre sélection répond à chaque usage. Livraison en Isère, financement flexible et reprise de votre véhicule actuel pour un changement de voiture sans souci à Grenoble.',
    nearbyCitySlugs: ['lyon', 'saint-etienne', 'clermont-ferrand'],
  },
  {
    slug: 'dijon',
    name: 'Dijon',
    department: '21',
    region: 'Bourgogne-Franche-Comté',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/dijon.webp',
    description:
      'Dijon, capitale des Ducs de Bourgogne et cité gastronomique renommée, charme par son Palais ducal, ses toits vernissés et la route des Grands Crus à ses portes. Circuler dans la métropole dijonnaise, de Fontaine-d\'Ouche à Chenôve en passant par le centre historique, demande un véhicule fiable toute l\'année. Activ Automobiles propose aux Dijonnais un large choix de voitures d\'occasion vérifiées et garanties 12 mois. Citadine pour la ville, break pour les balades viticoles en Côte-d\'Or ou SUV pour les hivers bourguignons : nos véhicules répondent à tous les besoins. Financement personnalisé, reprise au meilleur prix et livraison à domicile dans toute la Bourgogne.',
    nearbyCitySlugs: ['besancon', 'paris', 'lyon'],
  },
  {
    slug: 'angers',
    name: 'Angers',
    department: '49',
    region: 'Pays de la Loire',
    nearestAgencyId: 'agence-la-mothe-achard',
    nearestAgencyCity: 'La Mothe-Achard',
    heroImage: '/villes/angers.webp',
    description:
      'Angers, cité des Plantagenêt au bord de la Maine, séduit par son château médiéval, ses parcs verdoyants et sa douceur angevine légendaire. Ville à taille humaine, Angers offre une circulation agréable mais la voiture reste essentielle pour rejoindre les châteaux de la Loire ou le littoral vendéen. Activ Automobiles propose aux Angevins un catalogue complet de véhicules d\'occasion contrôlés et garantis 12 mois depuis l\'agence de La Mothe-Achard. Citadine pour les courses au quartier de la Doutre, SUV pour les escapades en Anjou ou berline pour les trajets vers Nantes : chaque auto est sélectionnée avec rigueur. Profitez d\'un financement adapté et d\'une livraison à domicile en Maine-et-Loire.',
    nearbyCitySlugs: ['nantes', 'le-mans', 'saint-nazaire'],
  },
  {
    slug: 'nancy',
    name: 'Nancy',
    department: '54',
    region: 'Grand Est',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/nancy.webp',
    description:
      'Nancy, joyau Art Nouveau du Grand Est, fascine par sa Place Stanislas dorée, ses grilles de Lamour et son patrimoine architectural exceptionnel. La métropole nancéienne, avec ses quartiers de Vandœuvre, Villers-lès-Nancy et Laxou, offre un réseau routier bien desservi par l\'A31 et l\'A33. Activ Automobiles vous accueille dans son agence de Nancy-Laxou, à quelques minutes du centre, avec un parc automobile varié et garanti 12 mois. De la citadine économique au SUV spacieux, chaque véhicule est rigoureusement inspecté par nos techniciens. Financement personnalisé, reprise de votre auto actuelle et livraison dans toute la Meurthe-et-Moselle : votre satisfaction est notre priorité à Nancy.',
    nearbyCitySlugs: ['strasbourg', 'reims', 'metz'],
  },
  {
    slug: 'metz',
    name: 'Metz',
    department: '57',
    region: 'Grand Est',
    nearestAgencyId: 'agence-talange',
    nearestAgencyCity: 'Talange',
    heroImage: '/villes/metz.webp',
    description:
      'Metz, ville millénaire sublimée par sa cathédrale Saint-Étienne aux vitraux de Chagall et son Centre Pompidou audacieux, est un carrefour stratégique du Grand Est. La métropole messine, entre Montigny-lès-Metz, Woippy et le Technopôle, s\'articule autour d\'un réseau autoroutier dense reliant Luxembourg, Strasbourg et Paris. Activ Automobiles Talange, à 10 minutes de Metz-Centre par l\'A31, vous propose un choix étendu de voitures d\'occasion contrôlées et garanties 12 mois. Berline pour les trajets transfrontaliers, citadine pour le centre-ville ou SUV familial : notre catalogue répond à chaque besoin. Financement souple, reprise au juste prix et livraison en Moselle garantis.',
    nearbyCitySlugs: ['strasbourg', 'reims', 'nancy'],
  },
  {
    slug: 'clermont-ferrand',
    name: 'Clermont-Ferrand',
    department: '63',
    region: 'Auvergne-Rhône-Alpes',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/clermont-ferrand.webp',
    description:
      'Clermont-Ferrand, berceau de Michelin au pied de la chaîne des Puys classée UNESCO, allie patrimoine volcanique et dynamisme industriel. La ville aux pierres noires de Volvic offre un cadre unique où la voiture est indispensable pour explorer les volcans d\'Auvergne et les villages du Puy-de-Dôme. Activ Automobiles propose aux Clermontois un catalogue riche de voitures d\'occasion vérifiées et garanties 12 mois. SUV pour gravir les routes de montagne, citadine pour la place de Jaude ou break pour les sorties familiales : nos techniciens inspectent chaque véhicule. Livraison à domicile, financement adapté et reprise de votre voiture actuelle pour un changement serein au cœur de l\'Auvergne.',
    nearbyCitySlugs: ['lyon', 'saint-etienne', 'grenoble'],
  },
  {
    slug: 'villeurbanne',
    name: 'Villeurbanne',
    department: '69',
    region: 'Auvergne-Rhône-Alpes',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/villeurbanne.webp',
    description:
      'Villeurbanne, ville dynamique intimement liée à Lyon, se distingue par ses Gratte-Ciel Art Déco, son campus de la Doua et sa vie culturelle foisonnante. À deux pas de la Part-Dieu et de la Presqu\'île lyonnaise, les Villeurbannais ont besoin d\'un véhicule pratique pour naviguer dans la métropole. Activ Automobiles offre un large choix de voitures d\'occasion inspectées et garanties 12 mois, parfaites pour la circulation métropolitaine et les escapades vers le Beaujolais ou les stations alpines. Citadine compacte, berline confortable ou SUV polyvalent : trouvez le véhicule adapté à votre mode de vie. Financement flexible, reprise avantageuse et livraison à domicile dans le Rhône.',
    nearbyCitySlugs: ['lyon', 'saint-etienne', 'grenoble'],
  },
  {
    slug: 'le-mans',
    name: 'Le Mans',
    department: '72',
    region: 'Pays de la Loire',
    nearestAgencyId: 'agence-rennes',
    nearestAgencyCity: 'Rennes',
    heroImage: '/villes/le-mans.webp',
    description:
      'Le Mans, célèbre pour ses 24 Heures mythiques et sa Cité Plantagenêt médiévale, est une ville à la croisée de l\'Ouest et du Bassin parisien. Les Manceaux, amateurs de belles mécaniques, apprécient un véhicule fiable pour leurs trajets dans la Sarthe et sur les routes vers Paris, Rennes ou Tours. Activ Automobiles propose un catalogue complet de voitures d\'occasion contrôlées et garanties 12 mois, accessible depuis notre agence de Rennes. Berline performante, citadine pratique ou SUV confortable : notre sélection honore la tradition automobile mancelle. Livraison à domicile dans la Sarthe, financement personnalisé et reprise de votre véhicule pour un achat en toute sérénité.',
    nearbyCitySlugs: ['nantes', 'angers', 'saint-nazaire'],
  },
  {
    slug: 'aix-en-provence',
    name: 'Aix-en-Provence',
    department: '13',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/aix-en-provence.webp',
    description:
      'Aix-en-Provence, ville d\'art et d\'eau, enchante par ses fontaines, le cours Mirabeau ombragé et les paysages de Cézanne. La cité aixoise, avec ses ruelles du vieil Aix et les axes rapides vers Marseille, demande un véhicule à la fois élégant et pratique. Activ Automobiles propose aux Aixois un choix soigné de voitures d\'occasion inspectées et garanties 12 mois, idéales pour circuler dans le pays d\'Aix et explorer les lavandes du Luberon. Berline raffinée, SUV pour les routes de Provence ou citadine pour le marché de la place Richelme : chaque véhicule est contrôlé par nos experts. Financement sur mesure, reprise et livraison dans les Bouches-du-Rhône.',
    nearbyCitySlugs: ['marseille', 'nice', 'toulon'],
  },
  {
    slug: 'brest',
    name: 'Brest',
    department: '29',
    region: 'Bretagne',
    nearestAgencyId: 'agence-rennes',
    nearestAgencyCity: 'Rennes',
    heroImage: '/villes/brest.webp',
    description:
      'Brest, cité maritime au bout du monde, fascine par sa rade immense, son château médiéval et Océanopolis. Les Brestois, habitués au climat océanique et aux routes du Finistère, ont besoin d\'un véhicule robuste et fiable en toute saison. Activ Automobiles propose un large catalogue de voitures d\'occasion vérifiées et garanties 12 mois, accessibles depuis notre agence de Rennes avec livraison dans tout le Finistère. SUV pour les sentiers côtiers de la presqu\'île de Crozon, citadine pour le centre de Brest ou break pour les familles : notre sélection couvre tous les besoins. Financement adapté, reprise de votre ancien véhicule et accompagnement expert pour rouler sereinement en Bretagne.',
    nearbyCitySlugs: ['rennes', 'nantes', 'le-havre'],
  },
  {
    slug: 'tours',
    name: 'Tours',
    department: '37',
    region: 'Centre-Val de Loire',
    nearestAgencyId: 'agence-la-mothe-achard',
    nearestAgencyCity: 'La Mothe-Achard',
    heroImage: '/villes/tours.webp',
    description:
      'Tours, jardin de la France au cœur des châteaux de la Loire, séduit par sa place Plumereau animée, ses maisons à colombages et ses vignobles de Vouvray. La métropole tourangelle, entre Saint-Cyr-sur-Loire, Joué-lès-Tours et Chambray, nécessite un véhicule confortable pour le quotidien et les escapades patrimoniales. Activ Automobiles offre aux Tourangeaux un catalogue de voitures d\'occasion contrôlées et garanties 12 mois depuis l\'agence de La Mothe-Achard. Berline pour les routes de Loire, citadine pour le vieux Tours ou SUV familial : notre équipe vous accompagne. Financement souple, reprise au meilleur prix et livraison en Indre-et-Loire pour un achat sans stress.',
    nearbyCitySlugs: ['orleans', 'paris', 'lyon'],
  },
  {
    slug: 'amiens',
    name: 'Amiens',
    department: '80',
    region: 'Hauts-de-France',
    nearestAgencyId: 'agence-talange',
    nearestAgencyCity: 'Talange',
    heroImage: '/villes/amiens.webp',
    description:
      'Amiens, fière de sa cathédrale gothique — la plus vaste de France — et de ses hortillonnages poétiques, offre un cadre de vie où la voiture reste essentielle. De la gare du Nord aux quartiers de Saint-Leu et Henriville, les Amiénois circulent entre centre-ville et périphérie pour rejoindre la baie de Somme ou Paris. Activ Automobiles vous propose un large choix de voitures d\'occasion inspectées et garanties 12 mois, avec livraison dans toute la Somme. Citadine économique, berline confortable ou SUV polyvalent : chaque véhicule est vérifié par nos techniciens certifiés. Profitez d\'un financement personnalisé et d\'une reprise transparente pour votre prochain achat à Amiens.',
    nearbyCitySlugs: ['lille', 'dunkerque', 'calais'],
  },
  {
    slug: 'limoges',
    name: 'Limoges',
    department: '87',
    region: 'Nouvelle-Aquitaine',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/limoges.webp',
    description:
      'Limoges, capitale des arts du feu célèbre pour sa porcelaine et ses émaux, charme par sa gare Bénédictins Art Déco et ses quartiers médiévaux. La préfecture de la Haute-Vienne, entourée de campagnes limousines, nécessite un véhicule fiable pour les trajets urbains comme pour les escapades vers les monts de Blond ou le lac de Vassivière. Activ Automobiles propose aux Limougeauds un catalogue de voitures d\'occasion vérifiées et garanties 12 mois. Break pour les routes de campagne, citadine pour le centre ou SUV pour les hivers en altitude : notre sélection est variée. Livraison en Haute-Vienne, financement adapté et reprise de votre ancien véhicule pour simplifier votre achat.',
    nearbyCitySlugs: ['bordeaux', 'pau', 'la-rochelle'],
  },
  {
    slug: 'perpignan',
    name: 'Perpignan',
    department: '66',
    region: 'Occitanie',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/perpignan.webp',
    description:
      'Perpignan, porte de la Catalogne baignée de soleil, rayonne par son Palais des Rois de Majorque, son Castillet coloré et sa proximité avec l\'Espagne et les plages du Roussillon. Les Perpignanais, entre centre-ville animé et escapades vers Collioure ou Font-Romeu, ont besoin d\'un véhicule polyvalent. Activ Automobiles offre un catalogue de voitures d\'occasion contrôlées et garanties 12 mois, avec livraison dans les Pyrénées-Orientales. Cabriolet pour la côte, SUV pour les routes de montagne catalane ou citadine pour le marché de la place de la République : nos véhicules s\'adaptent à votre style de vie. Financement personnalisé et reprise avantageuse au programme.',
    nearbyCitySlugs: ['toulouse', 'montpellier', 'nimes'],
  },
  {
    slug: 'besancon',
    name: 'Besançon',
    department: '25',
    region: 'Bourgogne-Franche-Comté',
    nearestAgencyId: 'agence-epinal-chavelot',
    nearestAgencyCity: 'Épinal-Chavelot',
    heroImage: '/villes/besancon.webp',
    description:
      'Besançon, capitale comtoise enserrée dans une boucle du Doubs, impressionne par sa citadelle Vauban classée UNESCO et son savoir-faire horloger. La ville, entre collines boisées et quartiers comme Planoise ou Palente, nécessite un véhicule adapté aux dénivelés et aux hivers franc-comtois. Activ Automobiles, depuis l\'agence d\'Épinal-Chavelot, propose aux Bisontins un catalogue de voitures d\'occasion inspectées et garanties 12 mois. SUV pour les routes enneigées du Jura, citadine pour la Grande Rue piétonne ou break familial : notre offre couvre chaque besoin. Livraison dans le Doubs, financement flexible et reprise de votre véhicule pour un achat serein en Franche-Comté.',
    nearbyCitySlugs: ['dijon', 'paris', 'lyon'],
  },
  {
    slug: 'orleans',
    name: 'Orléans',
    department: '45',
    region: 'Centre-Val de Loire',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/orleans.webp',
    description:
      'Orléans, cité johannique sur les rives de la Loire, allie patrimoine historique et proximité parisienne. De la cathédrale Sainte-Croix aux quartiers de La Source et Saint-Marceau, les Orléanais apprécient la douceur ligérienne tout en ayant besoin d\'un véhicule pour rejoindre Paris, Tours ou Chartres. Activ Automobiles offre un catalogue varié de voitures d\'occasion contrôlées et garanties 12 mois, avec livraison dans le Loiret. Berline pour la N20, citadine pour le centre ou SUV pour les forêts de Sologne : chaque véhicule est rigoureusement inspecté. Profitez d\'un financement sur mesure et d\'une reprise transparente pour votre prochain achat automobile au cœur du Val de Loire.',
    nearbyCitySlugs: ['tours', 'paris', 'lyon'],
  },
  {
    slug: 'rouen',
    name: 'Rouen',
    department: '76',
    region: 'Normandie',
    nearestAgencyId: 'agence-rennes',
    nearestAgencyCity: 'Rennes',
    heroImage: '/villes/rouen.webp',
    description:
      'Rouen, capitale historique de Normandie, enchante par ses ruelles médiévales, sa cathédrale peinte par Monet et son Gros-Horloge Renaissance. La métropole rouennaise, entre les quais de Seine, le quartier Saint-Sever et les hauteurs de Mont-Saint-Aignan, demande un véhicule fiable pour la ville et les escapades vers les falaises d\'Étretat ou Giverny. Activ Automobiles propose aux Rouennais des voitures d\'occasion vérifiées et garanties 12 mois, avec livraison en Seine-Maritime. Citadine pour les rues historiques, break pour les familles ou SUV pour les routes normandes : notre sélection est complète. Financement personnalisé et reprise avantageuse pour un achat en toute confiance.',
    nearbyCitySlugs: ['le-havre', 'caen', 'paris'],
  },
  {
    slug: 'mulhouse',
    name: 'Mulhouse',
    department: '68',
    region: 'Grand Est',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/mulhouse.webp',
    description:
      'Mulhouse, cité industrielle et culturelle du sud de l\'Alsace, brille par ses musées techniques — dont la Cité de l\'Automobile — et sa Place de la Réunion colorée. Les Mulhousiens, à la croisée de la France, de l\'Allemagne et de la Suisse, ont besoin d\'un véhicule fiable pour les trajets transfrontaliers et le quotidien en ville. Activ Automobiles propose un catalogue de voitures d\'occasion inspectées et garanties 12 mois, avec livraison dans le Haut-Rhin. Berline pour l\'autoroute A36, citadine compacte pour le centre ou SUV pour les Vosges enneigées : notre expertise au service de votre mobilité. Financement adapté et reprise de votre véhicule actuel garantis.',
    nearbyCitySlugs: ['strasbourg', 'reims', 'nancy'],
  },
  {
    slug: 'caen',
    name: 'Caen',
    department: '14',
    region: 'Normandie',
    nearestAgencyId: 'agence-rennes',
    nearestAgencyCity: 'Rennes',
    heroImage: '/villes/caen.webp',
    description:
      'Caen, cité de Guillaume le Conquérant, allie mémoire historique et vitalité normande entre son château ducal et le Mémorial pour la Paix. Les Caennais circulent entre le centre-ville, Hérouville-Saint-Clair et les plages du Débarquement, nécessitant un véhicule confortable et endurant. Activ Automobiles, depuis son agence de Rennes, offre aux habitants du Calvados un large choix de voitures d\'occasion contrôlées et garanties 12 mois avec livraison à domicile. Citadine pratique pour la Prairie, SUV pour le bocage normand ou break pour les sorties familiales en bord de mer : notre catalogue répond à toutes les attentes. Financement souple et reprise avantageuse inclus.',
    nearbyCitySlugs: ['le-havre', 'rouen', 'paris'],
  },
  {
    slug: 'argenteuil',
    name: 'Argenteuil',
    department: '95',
    region: 'Île-de-France',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/argenteuil.webp',
    description:
      'Argenteuil, ville impressionniste des bords de Seine en Val-d\'Oise, offre un cadre résidentiel prisé aux portes de Paris et de La Défense. Les Argenteuillais, entre lignes de train et embouteillages franciliens, apprécient un véhicule fiable pour le quotidien et les week-ends hors de l\'Île-de-France. Activ Automobiles propose un catalogue de voitures d\'occasion inspectées et garanties 12 mois, avec livraison dans tout le Val-d\'Oise. Citadine compacte pour se faufiler sur les quais de Seine, berline pour l\'A15 ou SUV pour les escapades en Picardie : nos véhicules sont rigoureusement sélectionnés. Financement personnalisé, reprise de votre auto et accompagnement dédié pour votre prochain achat.',
    nearbyCitySlugs: ['paris', 'saint-denis', 'montreuil'],
  },
  {
    slug: 'saint-denis',
    name: 'Saint-Denis',
    department: '93',
    region: 'Île-de-France',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/saint-denis.webp',
    description:
      'Saint-Denis, ville du Stade de France et de la basilique royale, est au cœur du Grand Paris en pleine transformation. Les Dionysiens, entre la ligne 13, la future ligne 15 et un réseau routier dense, trouvent dans la voiture un allié indispensable pour leurs déplacements professionnels et familiaux. Activ Automobiles offre un large choix de voitures d\'occasion vérifiées et garanties 12 mois, avec livraison en Seine-Saint-Denis. Citadine pour la ville, berline confortable pour l\'A1 ou SUV polyvalent pour les week-ends : chaque véhicule passe un contrôle complet. Financement adapté à tous les budgets et reprise au meilleur prix pour changer de voiture simplement à Saint-Denis.',
    nearbyCitySlugs: ['paris', 'argenteuil', 'montreuil'],
  },
  {
    slug: 'montreuil',
    name: 'Montreuil',
    department: '93',
    region: 'Île-de-France',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/montreuil.webp',
    description:
      'Montreuil, commune créative et multiculturelle aux portes de Paris, séduit par ses murs à pêches historiques et sa scène artistique vibrante. Les Montreuillois, connectés au métro mais souvent en quête d\'un véhicule pour les trajets vers la banlieue est ou les escapades hors Île-de-France, recherchent des autos fiables et accessibles. Activ Automobiles propose un catalogue de voitures d\'occasion contrôlées et garanties 12 mois, livrées directement à Montreuil. Citadine agile pour les rues de la Croix de Chavaux, SUV pour les sorties nature ou berline pour les longs trajets : notre sélection est variée et nos prix transparents. Financement flexible et reprise sans tracas.',
    nearbyCitySlugs: ['paris', 'argenteuil', 'saint-denis'],
  },
  {
    slug: 'dunkerque',
    name: 'Dunkerque',
    department: '59',
    region: 'Hauts-de-France',
    nearestAgencyId: 'agence-talange',
    nearestAgencyCity: 'Talange',
    heroImage: '/villes/dunkerque.webp',
    description:
      'Dunkerque, port du Nord légendaire pour son carnaval et son histoire héroïque, déploie ses charmes entre front de mer, beffroi et digue de Malo-les-Bains. Les Dunkerquois, exposés au vent marin et aux routes des Flandres, ont besoin d\'un véhicule robuste et bien entretenu. Activ Automobiles propose un catalogue de voitures d\'occasion inspectées et garanties 12 mois, avec livraison dans le Nord. SUV pour affronter le climat côtier, citadine pour le centre-ville ou break pour les familles : notre gamme couvre tous les besoins. Financement adapté, reprise de votre véhicule actuel et service personnalisé pour votre prochain achat automobile dans le Dunkerquois.',
    nearbyCitySlugs: ['lille', 'amiens', 'calais'],
  },
  {
    slug: 'valence',
    name: 'Valence',
    department: '26',
    region: 'Auvergne-Rhône-Alpes',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/valence.webp',
    description:
      'Valence, porte du Midi au bord du Rhône, séduit par son Kiosque Peynet, ses parcs verdoyants et sa gastronomie drômoise. Ville carrefour entre Lyon et la Provence, Valence est un point de départ idéal pour le Vercors ou l\'Ardèche. Activ Automobiles offre aux Valentinois un catalogue de voitures d\'occasion contrôlées et garanties 12 mois, avec livraison dans la Drôme. Berline confortable pour l\'autoroute du Soleil, SUV pour les gorges de l\'Ardèche ou citadine pour les boulevards du centre : notre sélection s\'adapte à votre quotidien. Financement flexible, reprise transparente et accompagnement expert pour votre achat automobile au cœur de la vallée du Rhône.',
    nearbyCitySlugs: ['lyon', 'saint-etienne', 'grenoble'],
  },
  {
    slug: 'avignon',
    name: 'Avignon',
    department: '84',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/avignon.webp',
    description:
      'Avignon, cité des Papes ceinte de remparts, fascine par son palais monumental, son célèbre pont et l\'effervescence de son festival estival. Les Avignonnais, entre intra-muros et les communes du Grand Avignon comme Le Pontet ou Villeneuve, ont besoin d\'un véhicule fiable pour circuler en Vaucluse et explorer le Luberon. Activ Automobiles propose un catalogue de voitures d\'occasion vérifiées et garanties 12 mois, avec livraison dans le Vaucluse. Cabriolet pour les routes de Provence, citadine pour les remparts ou SUV familial pour le mont Ventoux : chaque véhicule est contrôlé par nos techniciens. Financement sur mesure et reprise de votre ancien véhicule pour un changement serein.',
    nearbyCitySlugs: ['marseille', 'nice', 'toulon'],
  },
  {
    slug: 'nimes',
    name: 'Nîmes',
    department: '30',
    region: 'Occitanie',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/nimes.webp',
    description:
      'Nîmes, la Rome française, éblouit par ses Arènes parfaitement conservées, sa Maison Carrée et ses jardins de la Fontaine. Les Nîmois, entre centre historique et quartiers en expansion vers Caissargues ou Marguerittes, circulent dans une ville ensoleillée où la voiture est un compagnon quotidien. Activ Automobiles offre un large choix de voitures d\'occasion inspectées et garanties 12 mois, avec livraison dans le Gard. Citadine pour les ruelles de l\'Écusson, SUV pour les Cévennes ou berline pour les trajets vers Montpellier : notre catalogue répond à chaque usage. Financement adapté, reprise avantageuse et conseils personnalisés pour votre prochain achat automobile à Nîmes.',
    nearbyCitySlugs: ['toulouse', 'montpellier', 'perpignan'],
  },
  {
    slug: 'pau',
    name: 'Pau',
    department: '64',
    region: 'Nouvelle-Aquitaine',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/pau.webp',
    description:
      'Pau, ville royale au pied des Pyrénées, enchante par son Boulevard des Pyrénées offrant une vue spectaculaire, son château d\'Henri IV et son art de vivre béarnais. Les Palois, entre centre-ville élégant et routes de montagne vers les stations de ski ou les vallées d\'Ossau et d\'Aspe, recherchent des véhicules polyvalents. Activ Automobiles propose un catalogue de voitures d\'occasion contrôlées et garanties 12 mois, avec livraison dans les Pyrénées-Atlantiques. SUV pour les cols pyrénéens, citadine pour la ville ou break familial : chaque véhicule est inspecté avec soin. Financement personnalisé et reprise de votre véhicule actuel pour un achat automobile serein au pays du bon roi Henri.',
    nearbyCitySlugs: ['bordeaux', 'limoges', 'la-rochelle'],
  },
  {
    slug: 'la-rochelle',
    name: 'La Rochelle',
    department: '17',
    region: 'Nouvelle-Aquitaine',
    nearestAgencyId: 'agence-la-mothe-achard',
    nearestAgencyCity: 'La Mothe-Achard',
    heroImage: '/villes/la-rochelle.webp',
    description:
      'La Rochelle, perle de l\'Atlantique, séduit par ses tours médiévales, son Vieux-Port animé et son engagement écologique pionnier. Les Rochelais, entre centre historique piétonnier et plages de l\'île de Ré toute proche, ont besoin d\'un véhicule fiable pour profiter de la côte charentaise. Activ Automobiles, depuis l\'agence de La Mothe-Achard, offre un catalogue de voitures d\'occasion vérifiées et garanties 12 mois avec livraison en Charente-Maritime. Citadine pour le centre, SUV pour les escapades sur l\'île d\'Oléron ou break pour les vacances en famille : notre sélection est pensée pour la vie littorale. Financement souple et reprise de votre ancien véhicule garantis.',
    nearbyCitySlugs: ['bordeaux', 'limoges', 'pau'],
  },
  {
    slug: 'cannes',
    name: 'Cannes',
    department: '06',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/cannes.webp',
    description:
      'Cannes, capitale du cinéma mondial, brille par sa Croisette bordée de palaces, son Palais des Festivals et ses îles de Lérins. Les Cannois, entre mondanités et vie quotidienne dans le Suquet ou La Bocca, recherchent des véhicules alliant style et praticité. Activ Automobiles propose un catalogue de voitures d\'occasion inspectées et garanties 12 mois, avec livraison dans les Alpes-Maritimes. Berline élégante pour la Croisette, citadine pour le stationnement en centre-ville ou SUV pour les escapades dans le massif de l\'Esterel : nos véhicules sont rigoureusement sélectionnés. Financement personnalisé et reprise avantageuse pour un achat automobile digne de la French Riviera.',
    nearbyCitySlugs: ['marseille', 'nice', 'toulon'],
  },
  {
    slug: 'calais',
    name: 'Calais',
    department: '62',
    region: 'Hauts-de-France',
    nearestAgencyId: 'agence-talange',
    nearestAgencyCity: 'Talange',
    heroImage: '/villes/calais.webp',
    description:
      'Calais, sentinelle du détroit face à l\'Angleterre, allie patrimoine maritime, beffroi UNESCO et esprit de résilience. Les Calaisiens, habitués au climat marin et aux trajets vers Boulogne, Dunkerque ou le tunnel sous la Manche, comptent sur un véhicule robuste et bien entretenu. Activ Automobiles offre un catalogue de voitures d\'occasion contrôlées et garanties 12 mois, avec livraison dans le Pas-de-Calais. Berline pour les voyages vers l\'Angleterre, citadine pour le centre ou SUV pour la côte d\'Opale : notre sélection répond à chaque besoin. Financement adapté, reprise de votre auto actuelle et service personnalisé pour votre prochain achat dans le Calaisis.',
    nearbyCitySlugs: ['lille', 'amiens', 'dunkerque'],
  },
  {
    slug: 'antibes',
    name: 'Antibes',
    department: '06',
    region: 'Provence-Alpes-Côte d\'Azur',
    nearestAgencyId: 'agence-bordeaux',
    nearestAgencyCity: 'Bordeaux',
    heroImage: '/villes/antibes.webp',
    description:
      'Antibes, cité antique et balnéaire de la Côte d\'Azur, séduit par ses remparts, Port Vauban — le plus grand port de plaisance d\'Europe — et le cap d\'Antibes mythique. Les Antibois, entre vieille ville et Juan-les-Pins, naviguent dans une agglomération azuréenne dense où un véhicule agile est précieux. Activ Automobiles propose un catalogue de voitures d\'occasion vérifiées et garanties 12 mois, avec livraison dans les Alpes-Maritimes. Cabriolet pour les routes du littoral, citadine pour les marchés provençaux ou SUV pour les escapades dans l\'arrière-pays grassois : notre gamme s\'adapte à la vie méditerranéenne. Financement personnalisé et reprise transparente inclus.',
    nearbyCitySlugs: ['marseille', 'nice', 'toulon'],
  },
  {
    slug: 'saint-nazaire',
    name: 'Saint-Nazaire',
    department: '44',
    region: 'Pays de la Loire',
    nearestAgencyId: 'agence-la-mothe-achard',
    nearestAgencyCity: 'La Mothe-Achard',
    heroImage: '/villes/saint-nazaire.webp',
    description:
      'Saint-Nazaire, cité des grands paquebots et de l\'industrie navale, fascine par sa base sous-marine transformée en espace culturel et ses chantiers légendaires. Les Nazairiens, entre front de mer et quartiers comme Méan-Penhoët ou Ville-Port, ont besoin d\'un véhicule fiable pour leur quotidien en bord d\'estuaire. Activ Automobiles, depuis l\'agence de La Mothe-Achard, propose un catalogue de voitures d\'occasion inspectées et garanties 12 mois avec livraison en Loire-Atlantique. Citadine pour la ville, SUV pour les escapades vers la Brière ou break pour les sorties familiales sur la côte : notre sélection est complète. Financement adapté et reprise avantageuse garantis.',
    nearbyCitySlugs: ['nantes', 'angers', 'le-mans'],
  },
  {
    slug: 'colmar',
    name: 'Colmar',
    department: '68',
    region: 'Grand Est',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/colmar.webp',
    description:
      'Colmar, joyau de l\'Alsace avec sa Petite Venise pittoresque et ses maisons à colombages multicolores, est un écrin de charme au cœur du vignoble. Les Colmariens, entre vieille ville piétonne et routes des vins vers Riquewihr ou Kaysersberg, recherchent un véhicule à la fois pratique et confortable. Activ Automobiles propose un catalogue de voitures d\'occasion contrôlées et garanties 12 mois, avec livraison dans le Haut-Rhin. Citadine pour le centre historique, break pour les routes viticoles ou SUV pour les crêtes vosgiennes : chaque véhicule est vérifié par nos techniciens. Financement personnalisé et reprise transparente pour un achat serein en terre alsacienne.',
    nearbyCitySlugs: ['strasbourg', 'reims', 'nancy'],
  },
  {
    slug: 'troyes',
    name: 'Troyes',
    department: '10',
    region: 'Grand Est',
    nearestAgencyId: 'agence-nancy-laxou',
    nearestAgencyCity: 'Nancy-Laxou',
    heroImage: '/villes/troyes.webp',
    description:
      'Troyes, ville médiévale dont le centre forme un bouchon de champagne, charme par ses maisons à pans de bois, ses vitraux et ses magasins d\'usine réputés. Les Troyens, entre centre historique et zones commerciales de Pont-Sainte-Marie ou Saint-André-les-Vergers, apprécient un véhicule fiable pour le quotidien et les escapades en Champagne. Activ Automobiles propose un catalogue de voitures d\'occasion vérifiées et garanties 12 mois, avec livraison dans l\'Aube. Citadine pour les rues du centre, berline pour l\'autoroute A5 vers Paris ou SUV pour les lacs de la forêt d\'Orient : notre offre est variée. Financement souple, reprise au meilleur prix et accompagnement expert inclus.',
    nearbyCitySlugs: ['strasbourg', 'reims', 'nancy'],
  },
  {
    slug: 'poitiers',
    name: 'Poitiers',
    department: '86',
    region: 'Nouvelle-Aquitaine',
    nearestAgencyId: 'agence-la-mothe-achard',
    nearestAgencyCity: 'La Mothe-Achard',
    heroImage: '/villes/poitiers.webp',
    description:
      'Poitiers, ville d\'art et d\'histoire perchée sur son promontoire, impressionne par Notre-Dame la Grande, le Futuroscope voisin et son campus universitaire dynamique. Les Poitevins, entre centre médiéval et communes comme Buxerolles ou Chasseneuil, circulent dans une ville étudiante où les budgets comptent. Activ Automobiles, depuis l\'agence de La Mothe-Achard, offre un catalogue de voitures d\'occasion contrôlées et garanties 12 mois avec livraison dans la Vienne. Citadine économique pour les étudiants, break pour les familles ou SUV pour les sorties dans le Marais Poitevin : nos prix sont compétitifs. Financement adapté et reprise de votre véhicule pour un achat simplifié.',
    nearbyCitySlugs: ['bordeaux', 'limoges', 'pau'],
  },
];

export function getCityBySlug(slug: string): SEOCity | undefined {
  return SEO_CITIES.find((c) => c.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return SEO_CITIES.map((c) => c.slug);
}