/**
 * SpiderVO Vehicle Data
 *
 * Reads pre-built vehicle data from lib/data/spidervo-vehicles.json.
 * The JSON is generated at build time by scripts/prebuild-spidervo.mjs
 * to avoid runtime fetch timeouts on Vercel Hobby (10s limit).
 *
 * The prebuild script runs before `next build` and fetches the full
 * SpiderVO XML feed (~8MB, ~15s), parses it, and saves as JSON.
 */

import type { Vehicle } from '@/lib/types';

// Import the pre-built JSON data
// This file is generated by: node scripts/prebuild-spidervo.mjs
import vehiclesData from '@/lib/data/spidervo-vehicles.json';

// ─── Cached export ──────────────────────────────────────────────────────────

export async function getSpiderVOVehicles(): Promise<Vehicle[]> {
  return vehiclesData as Vehicle[];
}
